-- MySQL Script generated by MySQL Workbench
-- Thu May 11 09:50:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registroAtraso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `registroAtraso` ;

-- -----------------------------------------------------
-- Schema registroAtraso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registroAtraso` DEFAULT CHARACTER SET utf8 ;
USE `registroAtraso` ;

-- -----------------------------------------------------
-- Table `registroAtraso`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registroAtraso`.`funcionarios` ;

CREATE TABLE IF NOT EXISTS `registroAtraso`.`funcionarios` (
  `rut_func` VARCHAR(14) NOT NULL,
  `nombre_func` VARCHAR(45) NOT NULL,
  `apellido_func` VARCHAR(45) NOT NULL,
  `email_func` VARCHAR(45) NOT NULL,
  `password_func` VARCHAR(60) NOT NULL,
  `admin_func` BOOL NOT NULL,
  PRIMARY KEY (`rut_func`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroAtraso`.`Apoderado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registroAtraso`.`apoderados` ;

CREATE TABLE IF NOT EXISTS `registroAtraso`.`apoderados` (
  `nombre_apoderado` VARCHAR(25) NOT NULL,
  `apellido_apoderado` VARCHAR(45) NOT NULL,
  `rut_apoderado` VARCHAR(14) NOT NULL,
  `password_apoderado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut_apoderado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroAtraso`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registroAtraso`.`estudiantes` ;

CREATE TABLE IF NOT EXISTS `registroAtraso`.`estudiantes` (
  `rut_estudiante` VARCHAR(14) NOT NULL,
  `nombres_estudiante` VARCHAR(70) NOT NULL,
  `apellidos_estudiante` VARCHAR(70) NOT NULL,
  `curso_estudiante` VARCHAR(3) NOT NULL,
  `rut_apoderado` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`rut_estudiante`),
  INDEX `fk_Estudiante_Apoderado_idx` (`rut_apoderado` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Apoderado`
    FOREIGN KEY (`rut_apoderado`)
    REFERENCES `registroAtraso`.`apoderados` (`rut_apoderado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroAtraso`.`Atraso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registroAtraso`.`atrasos` ;

CREATE TABLE IF NOT EXISTS `registroAtraso`.`atrasos` (
  `id_atraso` INT NOT NULL,
  `fecha_atraso` DATE NOT NULL,
  `hora_atraso` DATETIME NOT NULL,
  `rut_estudiante` VARCHAR(14) NULL,
  `rut_func` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_atraso`, `rut_func`),
  INDEX `fk_Atraso_Funcionario_idx` (`rut_func` ASC) VISIBLE,
  INDEX `fk_Atraso_Estudiante_idx` (`rut_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_Atraso_Funcionario`
    FOREIGN KEY (`rut_func`)
    REFERENCES `registroAtraso`.`funcionarios` (`rut_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atraso_Estudiante`
    FOREIGN KEY (`rut_estudiante`)
    REFERENCES `registroAtraso`.`estudiantes` (`rut_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
